### ISSUE TITLE
Error when importing CPI: sqlite3.OperationalError: no such table: cu.area

### ISSUE THREAD

**Issue by davidr99** [palewire/cpi#62]
Version 1.0.5 works, but the newest verison 1.0.9 does not.  It gives me this no such table error as seen below.  It looks like it may be missing a DB file or some issues with the DB file its self:

```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\cpi\__init__.py", line 21, in <module>
    areas = parsers.ParseArea().parse()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cpi\parsers.py", line 60, in parse
    for row in self.get_file("cu.area"):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cpi\parsers.py", line 37, in get_file
    query = cursor.execute(f'SELECT * FROM "{file}"')
sqlite3.OperationalError: no such table: cu.area
>>>
```

**Comment by palewire** [comment]
I think I may have left a key step out of the release command. Hold tight.

**Comment by palewire** [comment]
Just sent a new cut. Try:

```
pipenv install cpi==1.0.10
```

And another run.

**Comment by davidr99** [comment]
Yep that fixed it!  Thanks!

**Comment by palewire** [comment]
Great. Thanks for flagging the problem.
